"""add_deep_research_fields

Revision ID: 0e85cb793764
Revises: 710917a4f94b
Create Date: 2026-06-14 13:42:39.808154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e85cb793764'
down_revision: Union[str, None] = '710917a4f94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_logs', sa.Column('planner_latency', sa.Float(), nullable=True))
    op.add_column('evaluation_logs', sa.Column('research_latency', sa.Float(), nullable=True))
    op.add_column('evaluation_logs', sa.Column('aggregation_latency', sa.Float(), nullable=True))
    op.add_column('evaluation_logs', sa.Column('sub_question_count', sa.Integer(), nullable=True))
    op.add_column('evaluation_logs', sa.Column('evidence_count', sa.Integer(), nullable=True))
    op.add_column('evaluation_logs', sa.Column('research_depth', sa.String(length=50), nullable=True))
    op.add_column('evaluation_logs', sa.Column('faithfulness_score', sa.Float(), nullable=True))
    op.add_column('evaluation_logs', sa.Column('answer_relevancy_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation_logs', 'answer_relevancy_score')
    op.drop_column('evaluation_logs', 'faithfulness_score')
    op.drop_column('evaluation_logs', 'research_depth')
    op.drop_column('evaluation_logs', 'evidence_count')
    op.drop_column('evaluation_logs', 'sub_question_count')
    op.drop_column('evaluation_logs', 'aggregation_latency')
    op.drop_column('evaluation_logs', 'research_latency')
    op.drop_column('evaluation_logs', 'planner_latency')
    # ### end Alembic commands ###
