"""add adaptive retrieval fields

Revision ID: 710917a4f94b
Revises: 9914798eb793
Create Date: 2026-06-13 18:59:08.061407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710917a4f94b'
down_revision: Union[str, None] = '9914798eb793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_logs', sa.Column('adaptive_retrieval_used', sa.Boolean(), nullable=True))
    op.add_column('evaluation_logs', sa.Column('retrieval_attempts', sa.Integer(), nullable=True))
    op.add_column('evaluation_logs', sa.Column('evidence_expansion_factor', sa.Float(), nullable=True))
    op.add_column('evaluation_logs', sa.Column('verification_improvement', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation_logs', 'verification_improvement')
    op.drop_column('evaluation_logs', 'evidence_expansion_factor')
    op.drop_column('evaluation_logs', 'retrieval_attempts')
    op.drop_column('evaluation_logs', 'adaptive_retrieval_used')
    # ### end Alembic commands ###
